@Net.Code.Kbo.Api_HostAddress = http://localhost:5063

GET {{Net.Code.Kbo.Api_HostAddress}}/companies/0476.893.174

###
GET {{Net.Code.Kbo.Api_HostAddress}}/companies/BE0669521714

###
GET {{Net.Code.Kbo.Api_HostAddress}}/companies/0476.893.174?language=FR

###
GET {{Net.Code.Kbo.Api_HostAddress}}/companies/0403.278.488

###
GET {{Net.Code.Kbo.Api_HostAddress}}/companies?name=kbc&language=NL

###

GET {{Net.Code.Kbo.Api_HostAddress}}/companies?name=mensura&language=NL

###

GET {{Net.Code.Kbo.Api_HostAddress}}/companies/0459.526.909

###

GET {{Net.Code.Kbo.Api_HostAddress}}/companies/search?text=Betaling%20Bancontact%2029%2F03%2F25%20-%2010.41%20uur%20-%20ALBERT%20HEIJN%203132%20HASS%203511%20-%20HASSELT%20-%20BEL%20Kaartnummer%205229%2062XX%20XXXX%200390

###

GET {{Net.Code.Kbo.Api_HostAddress}}/companies/0725.954.928